### ISSUE TITLE
User credentials are missing

### ISSUE THREAD

**Issue by MaXGitteR** [gameblabla/retrostone2-buildroot#3]
User credentials (User and root) are missing
cfw123

**Comment by gameblabla** [comment]
You can't boot as root as it's intentional. Also, user is passwordless and the username is od. That said, i haven't messed too much with it and besides, what are you trying to do with it ?
The rootfs is mounted as read-only by default. If you just want to insert some skins, you can already do so in your NTFS partition.
As for booting to other GUIs, that's already possible.
